Repository ginkgo-project/ginkgo, pull requests merged in 2018-08, with the labels that each got.

#95 Improve CUDA implementation of the ELL format
  cuda/matrix/ell_kernels.cu
Labels: CUDA, Enhancement

#99 Put the `ByInteraction` criterion outside of `gko::stop` namespace
  examples/asynchronous_stopping_criterion/asynchronous_stopping_criterion.cpp
Labels: Enhancement, Example

#102 Add a minimal example for solving a system
  examples/CMakeLists.txt
  examples/minimal_solver_cuda/CMakeLists.txt
  examples/minimal_solver_cuda/build.sh
  examples/minimal_solver_cuda/data/A.mtx
  examples/minimal_solver_cuda/data/b.mtx
  examples/minimal_solver_cuda/data/x0.mtx
  examples/minimal_solver_cuda/minimal_solver_cuda.cpp
Labels: Example, Task

#103 Simple spmv
  CMakeLists.txt
  benchmark/CMakeLists.txt
  benchmark/spmv_comparison_cuda/CMakeLists.txt
  benchmark/spmv_comparison_cuda/additional_check.patch
  benchmark/spmv_comparison_cuda/build.sh
  benchmark/spmv_comparison_cuda/spmv_comparison_cuda.cpp
  cmake/detect_gpu.cmake
  cuda/CMakeLists.txt
  include/ginkgo.hpp
Labels: Benchmarking, Task

#104 Fix for unnecessary copies in stopping criteria
  core/stop/combined.hpp
  core/stop/iteration.hpp
  core/stop/residual_norm_reduction.hpp
  examples/asynchronous_stopping_criterion/asynchronous_stopping_criterion.cpp
Labels: Bug, Core

#106 Add document with more details about licensing
  ABOUT-LICENSING.md
  README.md
Labels: Documentation

#100 Gmres core and reference
  core/CMakeLists.txt
  core/base/exception_helpers.hpp
  core/base/types.hpp
  core/base/utils.hpp
  core/device_hooks/common_kernels.inc.cpp
  core/matrix/dense.hpp
  core/solver/gmres.cpp
  core/solver/gmres.hpp
  core/solver/gmres_kernels.hpp
  core/stop/criterion.hpp
  core/test/base/exception_helpers.cpp
  core/test/matrix/dense.cpp
  core/test/solver/CMakeLists.txt
  core/test/solver/gmres.cpp
  cuda/CMakeLists.txt
  cuda/matrix/dense_kernels.cu
  cuda/solver/gmres_kernels.cu
  dev_tools/scripts/create_new_algorithm.sh
  omp/CMakeLists.txt
  omp/matrix/dense_kernels.cpp
  omp/solver/gmres_kernels.cpp
  reference/CMakeLists.txt
  reference/matrix/dense_kernels.cpp
  reference/solver/gmres_kernels.cpp
  reference/test/solver/CMakeLists.txt
  reference/test/solver/gmres_kernels.cpp
Labels: Core, Reference, Task

#111 Fix double EnableLogging definition in solvers
  core/solver/bicgstab.hpp
  core/solver/cg.hpp
  core/solver/cgs.hpp
  core/solver/fcg.hpp
Labels: Bug, Core

#112 Solver benchmark
  ABOUT-LICENSING.md
  CMakeLists.txt
  README.md
  benchmark/CMakeLists.txt
  benchmark/solver/CMakeLists.txt
  benchmark/solver/solver.cpp
  third_party/CMakeLists.txt
  third_party/gflags/CMakeLists.txt
  third_party/git-cmake-format/CMakeLists.txt
  third_party/rapidjson/CMakeLists.txt
Labels: Benchmarking, Task

#114 fix benchmark/spmv CI failed
  benchmark/spmv/spmv.cpp
Labels: Benchmarking, Bug

#118 Fix for linking errors with CMake 3.12
  third_party/gtest/CMakeLists.txt
Labels: Bug, Build

#119 move benchmark output into objects
  benchmark/solver/solver.cpp
  benchmark/spmv/spmv.cpp
Labels: Benchmarking, Enhancement

#120 Benchmark integration with the CI system
  .gitlab-ci.yml
  CMakeLists.txt
  benchmark/CMakeLists.txt
  benchmark/run_all_benchmarks.sh
  benchmark/spmv/spmv.cpp
  third_party/CMakeLists.txt
Labels: Benchmarking, Build, CI/CD, Enhancement

#121 Report memory consumption in SpMV benchmark
  benchmark/spmv/spmv.cpp
  core/base/executor.hpp
  core/device_hooks/cuda_hooks.cpp
  core/devices/omp/executor.cpp
  core/test/base/executor.cpp
  cuda/base/executor.cpp
Labels: Benchmarking, Bug, Enhancement
