Repository ginkgo-project/ginkgo, pull requests merged in 2018-04, with the labels that each got.

#22 CGS solver classes and reference kernels
  core/CMakeLists.txt
  core/device_hooks/common_kernels.inc.cpp
  core/solver/cgs.cpp
  core/solver/cgs.hpp
  core/solver/cgs_kernels.hpp
  core/test/solver/CMakeLists.txt
  core/test/solver/cgs.cpp
  cpu/CMakeLists.txt
  cpu/solver/cgs_kernels.cpp
  gpu/CMakeLists.txt
  gpu/solver/cgs_kernels.cu
  gpu/test/solver/cgs_kernels.cpp
  reference/CMakeLists.txt
  reference/solver/cgs_kernels.cpp
  reference/test/solver/CMakeLists.txt
  reference/test/solver/cgs_kernels.cpp
Labels: task

#34 Preconditioned solver example
  examples/CMakeLists.txt
  examples/preconditioned_solver/CMakeLists.txt
  examples/preconditioned_solver/build.sh
  examples/preconditioned_solver/data/A.mtx
  examples/preconditioned_solver/data/b.mtx
  examples/preconditioned_solver/data/x0.mtx
  examples/preconditioned_solver/preconditioned_solver.cpp
  include/ginkgo.hpp
Labels: task

#20 Add support for Multiple GPUs
  core/base/executor.hpp
  core/device_hooks/gpu_hooks.cpp
  gpu/base/executor.cpp
  gpu/test/base/gpu_executor.cu
Labels: bug, proposal

#19 Automatically detect GPU architecture/code flags during CMake configure step
  CMakeLists.txt
  cmake/detect_gpu.cmake
  gpu/CMakeLists.txt
Labels: task

#40 this bugfix resolves the reading of invalid data
  examples/preconditioned_solver/preconditioned_solver.cpp
  examples/simple_solver/simple_solver.cpp
Labels: bug

#35 CGS GPU kernels
  core/matrix/dense.hpp
  core/solver/cgs.hpp
  gpu/CMakeLists.txt
  gpu/solver/cgs_kernels.cu
  gpu/test/solver/CMakeLists.txt
  gpu/test/solver/cgs_kernels.cpp
  reference/solver/cgs_kernels.cpp
  reference/test/matrix/coo_kernels.cpp
Labels: task

#44 fix the CGS tester by modifying the call to the matrix generator
  gpu/test/solver/cgs_kernels.cpp
Labels: bug

#31 Memory utilities
  core/base/utils.hpp
  core/test/base/utils.cpp
  examples/ginkgo_overhead/ginkgo_overhead.cpp
  examples/preconditioned_solver/preconditioned_solver.cpp
  examples/simple_solver/simple_solver.cpp
Labels: enhancement, proposal

#42 Generation script improvements
  dev_tools/scripts/create_new_algorithm.sh
  gpu/matrix/csr_kernels.cu
Labels: enhancement, proposal
