Repository ginkgo-project/ginkgo, pull requests merged in 2018-10, with the labels that each got.

#142 Fix GPU compilation for newer CUDA versions
  CMakeLists.txt
  README.md
  cmake/detect_gpu.cmake
  cuda/CMakeLists.txt
  third_party/CMakeLists.txt
  third_party/CudaArchitectureSelector/CMakeLists.txt
  third_party/package_loader.cmake
Labels: Bug, Build, Enhancement

#137 Cooperative groups
  core/base/utils.hpp
  cuda/components/cooperative_groups.cuh
  cuda/components/diagonal_block_manipulation.cuh
  cuda/components/reduction.cuh
  cuda/components/shuffle.cuh
  cuda/components/synchronization.cuh
  cuda/components/warp_blas.cuh
  cuda/matrix/dense_kernels.cu
  cuda/preconditioner/block_jacobi_kernels.cu
Labels: Bug, CUDA, Enhancement

#141 Fix CuBLAS norm2 calls.
  core/matrix/dense.hpp
  cuda/CMakeLists.txt
  cuda/base/cublas_bindings.hpp
  cuda/components/zero_array.cu
  cuda/components/zero_array.hpp
  cuda/matrix/dense_kernels.cu
Labels: Bug, Confirmed

#150 Add method for removing loggers
  core/log/logger.hpp
  core/test/log/logger.cpp
Labels: Core, Enhancement

#149 Better ctest integration and memory checking
  CMakeLists.txt
  core/matrix/dense.hpp
  core/matrix/sellp.cpp
  core/test/matrix/sellp.cpp
  dev_tools/valgrind/suppressions.supp
  reference/test/preconditioner/block_jacobi.cpp
  reference/test/stop/iteration.cpp
  reference/test/stop/time.cpp
  third_party/gflags/CMakeLists.txt
Labels: Bug, Build, Enhancement, Testing

#153 Add basic matrix generation utility
  benchmark/CMakeLists.txt
  benchmark/matrix_generator/CMakeLists.txt
  benchmark/matrix_generator/matrix_generator.cpp
Labels: Benchmarking, New feature

#151 Preconditioner benchmark
  benchmark/CMakeLists.txt
  benchmark/preconditioner/CMakeLists.txt
  benchmark/preconditioner/preconditioner.cpp
  core/base/name_demangling.hpp
Labels: Benchmarking, New feature

#155 Improved benchmark runner
  README.md
  benchmark/CMakeLists.txt
  benchmark/matrix_statistics/matrix_statistics.cpp
  benchmark/run_all_benchmarks.sh
Labels: Benchmarking, Enhancement

#157 Correctly handle CUDA builds with no GPUs
  third_party/CudaArchitectureSelector/CMakeLists.txt
Labels: Bug, Build

#158 Improved storage scheme for block-Jacobi
  core/preconditioner/block_jacobi.cpp
  cuda/components/warp_blas.cuh
  cuda/preconditioner/block_jacobi_kernels.cu
  reference/preconditioner/block_jacobi_kernels.cpp
  reference/test/preconditioner/block_jacobi_kernels.cpp
Labels: CUDA, Core, Enhancement, Reference
