Repository ginkgo-project/ginkgo, pull requests merged in 2018-06, with the labels that each got.

#49 Better support for custom value types
  CMakeLists.txt
  cmake/detect_gpu.cmake
  core/test/utils/assertions.hpp
  gpu/CMakeLists.txt
  gpu/base/cublas_bindings.hpp
  gpu/base/cusparse_bindings.hpp
  gpu/base/types.hpp
  gpu/components/reduction.cuh
  gpu/matrix/csr_kernels.cu
  gpu/matrix/dense_kernels.cpp
  gpu/matrix/dense_kernels.cu
  include/ginkgo.hpp
Labels: enhancement

#63 Add CUDA 9.2 to GPU detection script
  cmake/detect_gpu.cmake
Labels: enhancement

#57 COO GPU spmv kernel
  gpu/CMakeLists.txt
  gpu/components/atomic.cuh
  gpu/matrix/coo_kernels.cpp
  gpu/matrix/coo_kernels.cu
  gpu/test/matrix/CMakeLists.txt
  gpu/test/matrix/coo_kernels.cpp
Labels: task

#61 Hyb core
  core/CMakeLists.txt
  core/device_hooks/common_kernels.inc.cpp
  core/matrix/hybrid.cpp
  core/matrix/hybrid.hpp
  core/matrix/hybrid_kernels.hpp
  core/test/matrix/CMakeLists.txt
  core/test/matrix/hybrid.cpp
  cpu/CMakeLists.txt
  cpu/matrix/hybrid_kernels.cpp
  gpu/CMakeLists.txt
  gpu/matrix/hybrid_kernels.cpp
  reference/CMakeLists.txt
  reference/matrix/hybrid_kernels.cpp
Labels: task

#64 Fix atomic-related compilation issues for custom value types
  gpu/components/atomic.cuh
Labels: bug

#68 fix compile error of bitwise_not in gcc-5.5
  core/base/range.hpp
Labels: bug

#67 Random matrices with specific condition number
  core/base/matrix_data.hpp
  core/base/range.hpp
  core/base/range_accessors.hpp
  core/test/base/matrix_data.cpp
Labels: task
