Repository ginkgo-project/ginkgo, pull requests merged in 2019-01, with the labels that each got.

#196 Improved version of CAS
  third_party/CudaArchitectureSelector/CMakeLists.txt
Labels: Bug, Build

#199 Fix linking error for test cases
  cmake/create_test.cmake
Labels: Bug, Build, Core

#201 Add release builds and tests to the CI
  .gitlab-ci.yml
Labels: CI/CD, Enhancement

#202 Update the algorithm creation script to the recent Ginkgo changes.
  dev_tools/scripts/create_new_algorithm.sh
Labels: Bug

#195 Automatic generation of `ginkgo/ginkgo.hpp`
  CMakeLists.txt
  dev_tools/scripts/update_ginkgo_header.sh
  include/ginkgo/core/log/papi.hpp
  include/ginkgo/ginkgo.hpp
  include/ginkgo/ginkgo.hpp.in
Labels: Build, Core, Enhancement

#205 Fix handle location and some warnings
  cuda/base/executor.cpp
  cuda/matrix/coo_kernels.cu
  cuda/matrix/csr_kernels.cu
  include/ginkgo/core/base/lin_op.hpp
Labels: CUDA

#206 Add a GINKGO_VERBOSE_LEVEL option to CMake
  CMakeLists.txt
  README.md
  cuda/base/executor.cpp
  include/ginkgo/config.hpp.in
Labels: Build, xSDK

#211 Improve Ginkgo usage as a third party library
  cmake/GinkgoConfig.cmake.in
  cmake/install_helpers.cmake
Labels: Build, Help wanted

#197 improve Ell and add new Hybrid strategies
  benchmark/spmv/spmv.cpp
  core/test/matrix/hybrid.cpp
  cuda/matrix/ell_kernels.cu
  cuda/test/matrix/ell_kernels.cpp
  include/ginkgo/core/matrix/hybrid.hpp
  reference/test/matrix/dense_kernels.cpp
Labels: CUDA, Core, Enhancement, Matrix Format
