Repository ginkgo-project/ginkgo, pull requests merged in 2020-01, with the labels that each got.

#433 Use separate file for add_license.sh ignored files
  dev_tools/scripts/add_license.ignore
  dev_tools/scripts/add_license.sh
Labels: Build, READY TO MERGE

#434 Use demangled typename in error messages
  include/ginkgo/core/base/utils.hpp
Labels: READY TO MERGE

#441 add clang-format minimal requirement
  cmake/CTestScript.cmake
  third_party/git-cmake-format/CMakeLists.txt
Labels: Build, READY TO MERGE

#437 Add CsrBuilder and CooBuilder for intrusive access to matrix arrays
  core/matrix/coo_builder.hpp
  core/matrix/csr.cpp
  core/matrix/csr_builder.hpp
  core/matrix/csr_kernels.hpp
  core/test/matrix/CMakeLists.txt
  core/test/matrix/coo_builder.cpp
  core/test/matrix/csr_builder.cpp
  cuda/matrix/csr_kernels.cu
  dev_tools/scripts/add_license.ignore
  hip/matrix/csr_kernels.hip.cpp
  include/ginkgo/core/matrix/coo.hpp
  include/ginkgo/core/matrix/csr.hpp
  omp/matrix/csr_kernels.cpp
  reference/matrix/csr_kernels.cpp
Labels: Core, READY TO MERGE

#435 Auto-detect compilation settings based on present compilers/libraries
  CMakeLists.txt
  INSTALL.md
  cmake/autodetect_executors.cmake
  cmake/hip_path.cmake
Labels: Build, READY TO MERGE

#442 Disable GINKGO_DEVEL_TOOLS by default
  CMakeLists.txt
  INSTALL.md
  third_party/CMakeLists.txt
  third_party/dummy-hook/CMakeLists.txt
  third_party/dummy-hook/dummy_hook
Labels: Build, Helper scripts, READY TO MERGE

#429 Extract prefix sum computations
  core/components/prefix_sum.hpp
  cuda/CMakeLists.txt
  cuda/components/prefix_sum.cu
  cuda/factorization/par_ilu_kernels.cu
  cuda/matrix/csr_kernels.cu
  cuda/matrix/dense_kernels.cu
  cuda/matrix/ell_kernels.cu
  cuda/matrix/hybrid_kernels.cu
  cuda/matrix/sellp_kernels.cu
  cuda/matrix/sparsity_csr_kernels.cu
  cuda/test/components/CMakeLists.txt
  cuda/test/components/prefix_sum.cu
  hip/CMakeLists.txt
  hip/components/prefix_sum.hip.cpp
  hip/factorization/par_ilu_kernels.hip.cpp
  hip/matrix/csr_kernels.hip.cpp
  hip/matrix/dense_kernels.hip.cpp
  hip/matrix/ell_kernels.hip.cpp
  hip/matrix/hybrid_kernels.hip.cpp
  hip/matrix/sellp_kernels.hip.cpp
  hip/matrix/sparsity_csr_kernels.hip.cpp
  hip/test/components/CMakeLists.txt
  hip/test/components/prefix_sum.hip.cpp
  omp/CMakeLists.txt
  omp/components/prefix_sum.cpp
  omp/factorization/par_ilu_kernels.cpp
  omp/matrix/csr_kernels.cpp
  omp/test/CMakeLists.txt
  omp/test/components/CMakeLists.txt
  omp/test/components/prefix_sum.cpp
  reference/CMakeLists.txt
  reference/components/prefix_sum.cpp
  reference/factorization/par_ilu_kernels.cpp
  reference/matrix/csr_kernels.cpp
  reference/test/CMakeLists.txt
  reference/test/components/CMakeLists.txt
  reference/test/components/prefix_sum.cpp
  reference/test/factorization/par_ilu_kernels.cpp
Labels: Bug, READY TO MERGE, Technical Debt

#446 Pull in git-cmake-format fix
  third_party/git-cmake-format/CMakeLists.txt
Labels: Bug, Helper scripts, READY TO MERGE

#443 Specialize HIP cooperative groups for HCC and NVCC
  .gitlab-ci.yml
  cuda/test/components/CMakeLists.txt
  cuda/test/components/cooperative_groups.cu
  hip/components/cooperative_groups.hip.hpp
  hip/test/components/CMakeLists.txt
  hip/test/components/cooperative_groups.hip.cpp
Labels: HIP, READY TO MERGE

#452 Add CUDA header dependency to Lower and UpperTrs solver tests
  cmake/create_test.cmake
  cuda/components/atomic.cuh
  cuda/test/solver/CMakeLists.txt
Labels: Bug, Build, CUDA, READY TO MERGE, Testing

#453 Reduce compilation warnings
  core/base/extended_float.hpp
  hip/CMakeLists.txt
  include/ginkgo/core/base/range.hpp
Labels: Build, READY TO MERGE

#450 Fix CUDA compatibility of ginkgo.hpp
  CMakeLists.txt
  cmake/GinkgoConfig.cmake.in
  include/ginkgo/core/base/math.hpp
  include/ginkgo/core/stop/time.hpp
  test_install/CMakeLists.txt
  test_install/test_install_cuda.cu
Labels: Build, CUDA, READY TO MERGE
