Repository ginkgo-project/ginkgo, pull requests merged in 2020-03, with the labels that each got.

#465 Improve isfinite
  common/base/math.hpp.inc
  common/factorization/par_ilu_kernels.hpp.inc
  cuda/test/base/math.cu
  hip/test/base/math.hip.cpp
  include/ginkgo/core/base/math.hpp
Labels: Build, READY TO MERGE

#468 Cuda10.1 generic api: CSR and COO SpMV
  benchmark/utils/cuda_linops.hpp
  benchmark/utils/formats.hpp
  common/components/atomic.hpp.inc
  cuda/base/types.hpp
Labels: Benchmarking, CUDA, READY TO MERGE

#473 Fix windows cuda generic
  benchmark/conversions/conversions.cpp
  benchmark/matrix_generator/matrix_generator.cpp
  benchmark/matrix_statistics/matrix_statistics.cpp
  benchmark/preconditioner/preconditioner.cpp
  benchmark/solver/solver.cpp
  benchmark/spmv/spmv.cpp
  benchmark/utils/cuda_linops.hpp
  benchmark/utils/formats.hpp
  cuda/base/types.hpp
Labels: Bug, CUDA, READY TO MERGE, Windows

#470 An OSX build with Github actions
  .github/workflows/osx.yml
  README.md
  omp/CMakeLists.txt
  test_install/CMakeLists.txt
Labels: Apple, Build, CI/CD, READY TO MERGE

#469 Update Permutation class and kernels.
  common/matrix/dense_kernels.hpp.inc
  core/test/matrix/permutation.cpp
  cuda/matrix/dense_kernels.cu
  cuda/test/matrix/dense_kernels.cpp
  hip/matrix/dense_kernels.hip.cpp
  hip/test/matrix/dense_kernels.hip.cpp
  include/ginkgo/core/matrix/permutation.hpp
Labels: CUDA, Core, Enhancement, HIP, READY TO MERGE

#475 Add a private_ci tag for all our jobs.
  .gitlab-ci.yml
Labels: Bug, CI/CD, READY TO MERGE

#474 Reorder kernel parameters for consistency
  core/factorization/par_ilu.cpp
  core/matrix/coo.cpp
  core/matrix/coo_kernels.hpp
  core/matrix/csr.cpp
  core/matrix/csr_kernels.hpp
  core/matrix/dense.cpp
  core/matrix/dense_kernels.hpp
  core/matrix/ell.cpp
  core/matrix/ell_kernels.hpp
  core/matrix/hybrid.cpp
  core/matrix/hybrid_kernels.hpp
  core/matrix/sellp.cpp
  core/matrix/sellp_kernels.hpp
  core/matrix/sparsity_csr.cpp
  core/matrix/sparsity_csr_kernels.hpp
  cuda/matrix/coo_kernels.cu
  cuda/matrix/csr_kernels.cu
  cuda/matrix/dense_kernels.cu
  cuda/matrix/ell_kernels.cu
  cuda/matrix/hybrid_kernels.cu
  cuda/matrix/sellp_kernels.cu
  cuda/matrix/sparsity_csr_kernels.cu
  cuda/solver/common_trs_kernels.cuh
  hip/matrix/coo_kernels.hip.cpp
  hip/matrix/csr_kernels.hip.cpp
  hip/matrix/dense_kernels.hip.cpp
  hip/matrix/ell_kernels.hip.cpp
  hip/matrix/hybrid_kernels.hip.cpp
  hip/matrix/sellp_kernels.hip.cpp
  hip/matrix/sparsity_csr_kernels.hip.cpp
  hip/solver/common_trs_kernels.hip.hpp
  omp/matrix/coo_kernels.cpp
  omp/matrix/csr_kernels.cpp
  omp/matrix/dense_kernels.cpp
  omp/matrix/ell_kernels.cpp
  omp/matrix/hybrid_kernels.cpp
  omp/matrix/sellp_kernels.cpp
  omp/matrix/sparsity_csr_kernels.cpp
  omp/test/matrix/sparsity_csr_kernels.cpp
  reference/matrix/coo_kernels.cpp
  reference/matrix/csr_kernels.cpp
  reference/matrix/dense_kernels.cpp
  reference/matrix/ell_kernels.cpp
  reference/matrix/hybrid_kernels.cpp
  reference/matrix/sellp_kernels.cpp
  reference/matrix/sparsity_csr_kernels.cpp
  reference/test/matrix/sparsity_csr_kernels.cpp
Labels: READY TO MERGE, Technical Debt

#476 Replace valgrind by all sanitizers available.
  .gitlab-ci.yml
  CMakeLists.txt
  INSTALL.md
  README.md
  cmake/CTestScript.cmake
  cmake/build_type_helpers.cmake
  cmake/create_test.cmake
  core/test/base/CMakeLists.txt
  core/test/base/sanitizers.cpp
  dev_tools/containers/build_all_containers.sh
  dev_tools/containers/ginkgo-cuda-base.py
  dev_tools/containers/ginkgo-nocuda-base.py
  third_party/gtest/CMakeLists.txt
Labels: Build, CI/CD, Enhancement, Ready for review

#471 add windows ci setting
  .github/workflows/osx.yml
  .github/workflows/windows-build.yml
  CMakeLists.txt
  README.md
  cmake/GinkgoConfig.cmake.in
  cmake/build_helpers.cmake
  cmake/install_helpers.cmake
  cmake/windows_helpers.cmake
  omp/factorization/par_ilu_kernels.cpp
  test_install/CMakeLists.txt
Labels: CI/CD, READY TO MERGE, Windows

#481 Using next_krylov_basis instead of krylov_bases
  common/solver/gmres_kernels.hpp.inc
  core/solver/gmres.cpp
  core/solver/gmres_kernels.hpp
  cuda/solver/gmres_kernels.cu
  cuda/test/solver/gmres_kernels.cpp
  hip/solver/gmres_kernels.hip.cpp
  hip/test/solver/gmres_kernels.cpp
  omp/solver/gmres_kernels.cpp
  omp/test/solver/gmres_kernels.cpp
  reference/solver/gmres_kernels.cpp
Labels: Core, Enhancement, Might Affect Performance, READY TO MERGE, Solver

#484 update clang-format requirement and commit
  README.md
  third_party/git-cmake-format/CMakeLists.txt
Labels: Build, READY TO MERGE

#486 Improve RTTI use for error messages
  core/test/base/exception_helpers.cpp
  core/test/base/utils.cpp
  cuda/base/executor.cpp
  hip/base/executor.hip.cpp
  include/ginkgo/core/base/exception_helpers.hpp
  include/ginkgo/core/base/utils.hpp
Labels: READY TO MERGE

#488 ctest outputs the detail of failure
  .github/workflows/osx.yml
  .github/workflows/windows-build.yml
Labels: CI/CD, READY TO MERGE

#490 Fix MSVC C2398
  core/base/iterator_factory.hpp
Labels: READY TO MERGE, Windows
